# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mihail/study/simulated_annealing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mihail/study/simulated_annealing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mihail/study/simulated_annealing/CMakeFiles /Users/mihail/study/simulated_annealing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mihail/study/simulated_annealing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AnnealingScheduler

# Build rule for target.
AnnealingScheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnnealingScheduler
.PHONY : AnnealingScheduler

# fast build rule for target.
AnnealingScheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/build
.PHONY : AnnealingScheduler/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/main.cpp.s
.PHONY : main.cpp.s

src/BoltzmannCooling.o: src/BoltzmannCooling.cpp.o
.PHONY : src/BoltzmannCooling.o

# target to build an object file
src/BoltzmannCooling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/BoltzmannCooling.cpp.o
.PHONY : src/BoltzmannCooling.cpp.o

src/BoltzmannCooling.i: src/BoltzmannCooling.cpp.i
.PHONY : src/BoltzmannCooling.i

# target to preprocess a source file
src/BoltzmannCooling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/BoltzmannCooling.cpp.i
.PHONY : src/BoltzmannCooling.cpp.i

src/BoltzmannCooling.s: src/BoltzmannCooling.cpp.s
.PHONY : src/BoltzmannCooling.s

# target to generate assembly for a file
src/BoltzmannCooling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/BoltzmannCooling.cpp.s
.PHONY : src/BoltzmannCooling.cpp.s

src/CauchyCooling.o: src/CauchyCooling.cpp.o
.PHONY : src/CauchyCooling.o

# target to build an object file
src/CauchyCooling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/CauchyCooling.cpp.o
.PHONY : src/CauchyCooling.cpp.o

src/CauchyCooling.i: src/CauchyCooling.cpp.i
.PHONY : src/CauchyCooling.i

# target to preprocess a source file
src/CauchyCooling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/CauchyCooling.cpp.i
.PHONY : src/CauchyCooling.cpp.i

src/CauchyCooling.s: src/CauchyCooling.cpp.s
.PHONY : src/CauchyCooling.s

# target to generate assembly for a file
src/CauchyCooling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/CauchyCooling.cpp.s
.PHONY : src/CauchyCooling.cpp.s

src/ICoolingLaw.o: src/ICoolingLaw.cpp.o
.PHONY : src/ICoolingLaw.o

# target to build an object file
src/ICoolingLaw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ICoolingLaw.cpp.o
.PHONY : src/ICoolingLaw.cpp.o

src/ICoolingLaw.i: src/ICoolingLaw.cpp.i
.PHONY : src/ICoolingLaw.i

# target to preprocess a source file
src/ICoolingLaw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ICoolingLaw.cpp.i
.PHONY : src/ICoolingLaw.cpp.i

src/ICoolingLaw.s: src/ICoolingLaw.cpp.s
.PHONY : src/ICoolingLaw.s

# target to generate assembly for a file
src/ICoolingLaw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ICoolingLaw.cpp.s
.PHONY : src/ICoolingLaw.cpp.s

src/IMutation.o: src/IMutation.cpp.o
.PHONY : src/IMutation.o

# target to build an object file
src/IMutation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/IMutation.cpp.o
.PHONY : src/IMutation.cpp.o

src/IMutation.i: src/IMutation.cpp.i
.PHONY : src/IMutation.i

# target to preprocess a source file
src/IMutation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/IMutation.cpp.i
.PHONY : src/IMutation.cpp.i

src/IMutation.s: src/IMutation.cpp.s
.PHONY : src/IMutation.s

# target to generate assembly for a file
src/IMutation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/IMutation.cpp.s
.PHONY : src/IMutation.cpp.s

src/ISolution.o: src/ISolution.cpp.o
.PHONY : src/ISolution.o

# target to build an object file
src/ISolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ISolution.cpp.o
.PHONY : src/ISolution.cpp.o

src/ISolution.i: src/ISolution.cpp.i
.PHONY : src/ISolution.i

# target to preprocess a source file
src/ISolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ISolution.cpp.i
.PHONY : src/ISolution.cpp.i

src/ISolution.s: src/ISolution.cpp.s
.PHONY : src/ISolution.s

# target to generate assembly for a file
src/ISolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/ISolution.cpp.s
.PHONY : src/ISolution.cpp.s

src/LogarithmicCooling.o: src/LogarithmicCooling.cpp.o
.PHONY : src/LogarithmicCooling.o

# target to build an object file
src/LogarithmicCooling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/LogarithmicCooling.cpp.o
.PHONY : src/LogarithmicCooling.cpp.o

src/LogarithmicCooling.i: src/LogarithmicCooling.cpp.i
.PHONY : src/LogarithmicCooling.i

# target to preprocess a source file
src/LogarithmicCooling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/LogarithmicCooling.cpp.i
.PHONY : src/LogarithmicCooling.cpp.i

src/LogarithmicCooling.s: src/LogarithmicCooling.cpp.s
.PHONY : src/LogarithmicCooling.s

# target to generate assembly for a file
src/LogarithmicCooling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/LogarithmicCooling.cpp.s
.PHONY : src/LogarithmicCooling.cpp.s

src/SimulatedAnnealing.o: src/SimulatedAnnealing.cpp.o
.PHONY : src/SimulatedAnnealing.o

# target to build an object file
src/SimulatedAnnealing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/SimulatedAnnealing.cpp.o
.PHONY : src/SimulatedAnnealing.cpp.o

src/SimulatedAnnealing.i: src/SimulatedAnnealing.cpp.i
.PHONY : src/SimulatedAnnealing.i

# target to preprocess a source file
src/SimulatedAnnealing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/SimulatedAnnealing.cpp.i
.PHONY : src/SimulatedAnnealing.cpp.i

src/SimulatedAnnealing.s: src/SimulatedAnnealing.cpp.s
.PHONY : src/SimulatedAnnealing.s

# target to generate assembly for a file
src/SimulatedAnnealing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AnnealingScheduler.dir/build.make CMakeFiles/AnnealingScheduler.dir/src/SimulatedAnnealing.cpp.s
.PHONY : src/SimulatedAnnealing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AnnealingScheduler"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BoltzmannCooling.o"
	@echo "... src/BoltzmannCooling.i"
	@echo "... src/BoltzmannCooling.s"
	@echo "... src/CauchyCooling.o"
	@echo "... src/CauchyCooling.i"
	@echo "... src/CauchyCooling.s"
	@echo "... src/ICoolingLaw.o"
	@echo "... src/ICoolingLaw.i"
	@echo "... src/ICoolingLaw.s"
	@echo "... src/IMutation.o"
	@echo "... src/IMutation.i"
	@echo "... src/IMutation.s"
	@echo "... src/ISolution.o"
	@echo "... src/ISolution.i"
	@echo "... src/ISolution.s"
	@echo "... src/LogarithmicCooling.o"
	@echo "... src/LogarithmicCooling.i"
	@echo "... src/LogarithmicCooling.s"
	@echo "... src/SimulatedAnnealing.o"
	@echo "... src/SimulatedAnnealing.i"
	@echo "... src/SimulatedAnnealing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

